# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import Scrollbar
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import datetime


class schedule(QWidget):
  def __init__(self):
    super().__init__()
  def setupUi(self, Form, x, y):
        self.widget_border = QtWidgets.QLabel(Form)
        self.widget_border.setGeometry(QtCore.QRect(x+20, y+60, 480, 520))
        self.widget_border.setFrameShape(QtWidgets.QFrame.Box)
        self.widget_border.setText("")
        self.widget_border.setObjectName("widget_border")
        self.schedule_listWidget = QtWidgets.QListWidget(Form)
        self.schedule_listWidget.setGeometry(QtCore.QRect(x+30, y+120, 461, 451))
        self.schedule_listWidget.setObjectName("listWidget")
        self.schedule_listWidget.setStyleSheet( "QListWidget{background: black;} QScrollBar{ background-color: black; } ")
        self.schedule_listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(x+30, y+70, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 고딕 Std B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(x+350, y+80, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.addSchedule)
        self.retranslateschedule(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

  def retranslateschedule(self, Form):
      _translate = QtCore.QCoreApplication.translate
      Form.setWindowTitle(_translate("Form", "Form"))


      
      self.label.setText(_translate("Form", self.getDate()))
      self.pushButton.setText(_translate("Form", "PushButton"))
    
  def getSchedule(self): #데이터 베이스에서 스케쥴 호출
    pass

  def getDate(self):
    days  =["월","화","수", '목','금','토', '일']
    now = datetime.datetime.now()
    mdstr = " " + str(now.month) + "월 "+ str(now.day)+"일   "+ days[now.weekday()]
    return mdstr


  def addSchedule(self): #스케줄 리스트 위젯에 아이템 추가
   def get_item_wight():
    #     
    #ship_name = "park"
    #ship_photo = "a"
    #ship_index = "hello"
    #ship_type = "hello"
    #ship_country = "한국"
    #ship_star = "5개"
    ##  Widget
    #wight = QWidget()
    ##       
    #layout_main = QHBoxLayout()
    #map_l = QLabel() #     
    #map_l.setFixedSize(40, 25)
    ##maps = QPixmap(ship_photo).scaled(40, 25)
    #map_l.setPixmap(maps)
    ##        
    #layout_right = QVBoxLayout()
    ##         
    #layout_right_down = QHBoxLayout() #        
    #layout_right_down.addWidget(QLabel(ship_type))
    #layout_right_down.addWidget(QLabel(ship_country))
    #layout_right_down.addWidget(QLabel(str(ship_star) + " "))
    #layout_right_down.addWidget(QLabel(ship_index))
    ##       ,         
    #layout_main.addWidget(map_l) #       
    #layout_right.addWidget(QLabel(ship_name)) #        
    #layout_right.addLayout(layout_right_down) #        
    #layout_main.addLayout(layout_right) #      
    #wight.setLayout(layout_main) #    wight

    layout_main = QHBoxLayout()
    map1 = QLabel()
    map1.setStyleSheet( "QLabel{color: white;}")
    map1.setFixedWidth(340)
    map1.setFixedHeight(70)
    map1.setFrameShape(QtWidgets.QFrame.Box)
    map1.setText("Hello World")
    layout_main.addWidget(map1)
    
    map2 = QLabel()
    map2.setStyleSheet( "QLabel{color: white;}")
    map2.setFixedWidth(80)
    map2.setFixedHeight(70)
    map2.setFrameShape(QtWidgets.QFrame.Box)
    map2.setText("11AM\n1PM")
    layout_main.addWidget(map2)
    wight = QWidget()
    wight.setLayout(layout_main)
    return wight #   wight

   item = QListWidgetItem() #   QListWidgetItem  
   item.setSizeHint(QSize(200, 80)) #   QListWidgetItem 
   brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
   item.setBackground(brush)
   
   widget = get_item_wight() #            
   self.schedule_listWidget.addItem(item) #   item
   self.schedule_listWidget.setItemWidget(item, widget) #  item  widget