# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import Scrollbar
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import datetime
from db import db_access


class schedule(QWidget):
  def __init__(self):
    super().__init__()
  def setupUi(self, Form, x, y, user_id):
        self.widget_border = QtWidgets.QLabel(Form)
        self.widget_border.setGeometry(QtCore.QRect(x+20, y+60, 480, 520))
        self.widget_border.setFrameShape(QtWidgets.QFrame.Box)
        self.widget_border.setText("")
        self.widget_border.setObjectName("widget_border")
        self.schedule_listWidget = QtWidgets.QListWidget(Form)
        self.schedule_listWidget.setGeometry(QtCore.QRect(x+30, y+120, 461, 451))
        self.schedule_listWidget.setObjectName("listWidget")
        self.schedule_listWidget.setStyleSheet( "QListWidget{background: black;} QScrollBar{ background-color: black; } ")
        self.schedule_listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(x+30, y+70, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 고딕 Std B")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(x+350, y+80, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.addSchedule)
        self.retranslateschedule(Form)
        self.setSchedule(user_id)
        QtCore.QMetaObject.connectSlotsByName(Form)

  def retranslateschedule(self, Form):
      _translate = QtCore.QCoreApplication.translate
      Form.setWindowTitle(_translate("Form", "Form"))
      self.label.setText(_translate("Form", self.getDate()))
      self.pushButton.setText(_translate("Form", "PushButton"))
    
  def setSchedule(self,user_id): #데이터 베이스에서 스케쥴 호출
    data = db_access.get_schedule(user_id)
    for i in data:
      self.addSchedule(i)

  #날자 함수
  def getDate(self):
    days  =["월","화","수", '목','금','토', '일']
    now = datetime.datetime.now()
    mdstr = " " + str(now.month) + "월 "+ str(now.day)+"일   "+ days[now.weekday()]
    return mdstr

  #스케줄 아이템 추가 함수
  def addSchedule(self,data):
   def get_item_wight():
    layout_main = QHBoxLayout()
    map1 = QLabel()
    map1.setStyleSheet( "QLabel{color: white;}")
    map1.setFixedWidth(340)
    map1.setFixedHeight(70)
    map1.setFrameShape(QtWidgets.QFrame.Box)
    map1.setText(data[4]) #메시지 설정
    layout_main.addWidget(map1)
    
    map2 = QLabel()
    map2.setStyleSheet( "QLabel{color: white;}")
    map2.setFixedWidth(80)
    map2.setFixedHeight(70)
    map2.setFrameShape(QtWidgets.QFrame.Box)
    #map2.setText("11AM\n1PM")
    map2.setText(" %s:%s\n %s:%s" %(str(data[2].hour).zfill(2), str(data[2].minute).zfill(2), str(data[3].hour).zfill(2), str(data[3].minute).zfill(2)))
    layout_main.addWidget(map2)
    wight = QWidget()
    wight.setLayout(layout_main)
    return wight #   wight

   item = QListWidgetItem() 
   item.setSizeHint(QSize(200, 80))
   brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
   item.setBackground(brush)
   
   widget = get_item_wight()       
   self.schedule_listWidget.addItem(item) 
   self.schedule_listWidget.setItemWidget(item, widget)
