# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap,QIcon,QFont
from PyQt5.QtCore import Qt
from PyQt5.QtCore import QSize
import os


class camera(object):
    def setupUi(self, Form,x,y):

        self.frame = QtWidgets.QLabel(Form)
        self.frame.setGeometry(QtCore.QRect(x+20, y+60, 480, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setText("")
        self.frame.setObjectName("frame")

        icon_path= os.path.dirname(os.path.abspath(__file__)) #리소스 폴더 경로 추적
        #icon_path+="\\resource\weather_icon\weather_icon_001.png"
        pixmap = QPixmap(icon_path+"/resource/download.jpg")
        print(icon_path)
        pixmap = pixmap.scaled(480, 250, Qt.IgnoreAspectRatio) #아이콘 크기 설정
        self.frame.setPixmap(pixmap)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
