# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QSize
from PyQt5.QtCore import *
from db import db_access
from window import Layout_generator, Touch_Layout

class user(QWidget):
  def __init__(self):
    super().__init__()
  def setupUi(self, Form, x, y):
        self.data = []
        self.frame = QtWidgets.QLabel(Form)
        self.frame.setGeometry(QtCore.QRect(x+20, y+60, 480, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setText("")
        self.frame.setObjectName("frame")
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setGeometry(QtCore.QRect(x+30, y+65, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 고딕 Std B")
        font.setPointSize(15)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.name_view = QtWidgets.QListWidget(Form)
        self.name_view.setGeometry(QtCore.QRect(x+30, y+100, 460, 201))
        self.name_view.setStyleSheet("""color: #FFFFFF; 
                                        background-color: #000000;
                                        border-style: solid; 
                                        border-width: 1px; 
                                        border-color: #FFFFFF; 
                                        border-radius: 0px;
                                        font: 15pt """)
        self.name_view.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.name_view.itemClicked.connect(self.name_list_click)
        self.name_view.alternatingRowColors()
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name_view.setFont(font)
        self.name_view.setObjectName("name_view")
        
        self.retranslatesBelonging(Form)
        self.setUser()
        QtCore.QMetaObject.connectSlotsByName(Form)


  def retranslatesBelonging(self, Form):
      _translate = QtCore.QCoreApplication.translate
      Form.setWindowTitle(_translate("Form", "Form"))
      self.name_label.setText(_translate("Form", "유저목록"))

  def setUser(self):
    self.data = db_access.get_name()
    #print(self.data)
    for i in self.data:
      #print(i)
      self.adduser(i)

  def name_list_click(self):
          s = self.name_view.currentItem()
          form1 = QtWidgets.QDialog()
          ui = Touch_Layout.Ui_Form()
          ui.setupUi(form1,self.data[s.text()][1])
          form1.show()
          form1.exec_()
          del form1
    
  def adduser(self,str):
   #print(str)
   self.name_view.addItem(str)
  #  def get_item_wight():
  #   layout_main = QHBoxLayout()
  #   map1 = QLabel()
  #   map1.setStyleSheet( "QLabel{color: white;}")
  #   map1.setFixedWidth(420)
  #   map1.setFixedHeight(40)
  #   map1.setFrameShape(QtWidgets.QFrame.Box)
  #   map1.setText(str)
  #   map1.setStyleSheet("""color: #FFFFFF; 
  #                                       background-color: #000000;
  #                                       border-style: solid; 
  #                                       border-width: 1px; 
  #                                       border-color: #FFFFFF; 
  #                                       border-radius: 0px;
  #                                       font: 15pt """)
  #   layout_main.addWidget(map1)

  #   wight = QWidget()
  #   wight.setLayout(layout_main)
  #   return wight #   wight

  #  item = QListWidgetItem() #   QListWidgetItem  
  #  item.setSizeHint(QSize(420, 50)) #   QListWidgetItem 
  #  brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
  #  item.setBackground(brush)
   
  #  widget = get_item_wight() #            
  #  self.name_view.addItem(item) #   item
  #  self.name_view.setItemWidget(item, widget) #  item  widget