# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap,QIcon,QFont
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QSize
from PyQt5.QtCore import *

class message(QWidget):
  def __init__(self):
    super().__init__()
  def setupUi(self, Form, x, y):
        self.widget_border = QtWidgets.QLabel(Form)
        self.widget_border.setGeometry(QtCore.QRect(x+20, y+60, 480, 250))
        self.widget_border.setFrameShape(QtWidgets.QFrame.Box)
        self.widget_border.setText("")
        self.widget_border.setObjectName("widget_border")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(x+20, y+60, 480, 250))
        self.listWidget.setObjectName("listWidget")
        #self.listWidget.setStyleSheet("QListWidget::item { border: 0px solid red }")
        self.listWidget.setStyleSheet( "QListWidget{background: black;}")
        self.retranslatesMessage(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.addMessage()


  def retranslatesMessage(self, Form):
      _translate = QtCore.QCoreApplication.translate

  def addMessage(self):
   def get_item_wight():

    layout_main = QHBoxLayout()
    map1 = QLabel()
    map1.setStyleSheet( "QLabel{color: white;}")
    map1.setFixedWidth(60)
    map1.setFixedHeight(60)
    map1.setFrameShape(QtWidgets.QFrame.Box)
    map1.setText("BBBB")
    layout_main.addWidget(map1)
    
    map2 = QLabel()
    map2.setStyleSheet( "QLabel{color: white;}")
    map2.setFixedWidth(390)
    map2.setFixedHeight(60)
    map2.setFrameShape(QtWidgets.QFrame.Box)
    map2.setText("15000")
    layout_main.addWidget(map2)

    wight = QWidget()
    wight.setLayout(layout_main)
    return wight #   wight

   item = QListWidgetItem() #   QListWidgetItem  
   item.setSizeHint(QSize(200, 80)) #   QListWidgetItem 
   brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
   item.setBackground(brush)
   
   widget = get_item_wight() #            
   self.listWidget.addItem(item) #   item
   self.listWidget.setItemWidget(item, widget) #  item  widget