# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap,QIcon,QFont
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QSize
from PyQt5.QtCore import *
from db import db_access

class message(QWidget):
  def __init__(self):
    super().__init__()
  def setupUi(self, Form, x, y,user_id):
        self.frame = QtWidgets.QLabel(Form)
        self.frame.setGeometry(QtCore.QRect(x+20, y+60, 480, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setText("")
        self.frame.setObjectName("frame")
        self.message_label = QtWidgets.QLabel(Form)
        self.message_label.setGeometry(QtCore.QRect(x+30, y+65, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe 고딕 Std B")
        font.setPointSize(15)
        self.message_label.setFont(font)
        self.message_label.setObjectName("message_label")
        self.message_view = QtWidgets.QListWidget(Form)
        self.message_view.setGeometry(QtCore.QRect(x+30, y+100, 460, 201))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.message_view.setFont(font)
        self.message_view.setObjectName("message_view")
        
        self.retranslatesMessage(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.setMessage(user_id)


  def retranslatesMessage(self, Form):
      _translate = QtCore.QCoreApplication.translate
      Form.setWindowTitle(_translate("Form", "Form"))
      self.message_label.setText(_translate("Form", "메시지"))
  
  def setMessage(self, user_id):
    data = db_access.get_message(user_id)
    for i in data:
      self.addMessage(i)

  def addMessage(self,data):
   def get_item_wight():
    layout_main = QHBoxLayout()
    map1 = QLabel()
    map1.setStyleSheet( "QLabel{color: white;}")
    map1.setFixedWidth(60)
    map1.setFixedHeight(60)
    map1.setFrameShape(QtWidgets.QFrame.Box)
    map1.setText(data[7])
    layout_main.addWidget(map1)
    
    map2 = QLabel()
    map2.setStyleSheet( "QLabel{color: white;}")
    map2.setFixedWidth(370)
    map2.setFixedHeight(60)
    map2.setFrameShape(QtWidgets.QFrame.Box)
    map2.setText(data[3])
    layout_main.addWidget(map2)

    wight = QWidget()
    wight.setLayout(layout_main)
    return wight #   wight

   item = QListWidgetItem() #   QListWidgetItem  
   item.setSizeHint(QSize(200, 80)) #   QListWidgetItem 
   brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
   item.setBackground(brush)
   
   widget = get_item_wight() #            
   self.message_view.addItem(item) #   item
   self.message_view.setItemWidget(item, widget) #  item  widget